version: "3.8"

services:
  flask-app:
    container_name: my-flask-container
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        REQUESTS_VERSION: 2.32.4
    command: sh scripts/runner.sh
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=false
      - DATABASE_URL=mysql+pymysql://api:api123@db:3306/application
    restart: on-failure
    develop:
      watch:
        - path: ./app/requirements.txt
          action: rebuild
        - path: ./app
          action: sync+restart
          target: /app
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    networks:
      - full-stack
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - full-stack
    depends_on:
      - flask-app

  db:
    container_name: mysql
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword123
      - MYSQL_DATABASE=application
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api123
    networks:
      - full-stack
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  full-stack:
    driver: bridge

volumes:
  db-data:
