services:
  flask-app:
    container_name: my-flask-container
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - full-stack
    restart: unless-stopped

  nginx:
    image: nginx:latest
    networks:
      - full-stack

networks:
  full-stack:
    driver: bridge
